name: Build and deploy Node.js app to Azure Web App - super-kanban

on:
  push:
    branches:
    - master
  workflow_dispatch:


env:
  ACTIONS_STEP_DEBUG: true

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [ 20 ]
        angular-version: [ 16 ]
    steps:
    - uses: actions/checkout@v4
    - name: Install Angular CLI
      run: npm install -g @angular/cli@${{ matrix.angular-version }}

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install

    - name: Build Angular project
      run: pnpm build # Build the project using pnpm
    #- name: Run tests
    #  run: pnpm test # Run tests using pnpm
    - name: Zip artifact for deployment
      run: zip -r release.zip dist/

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D9CB3265C91847549C832FAF2DB1B281 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3A747CE3D4C140249790904B34CBD9F4 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EDF9A35B0B504167A1BF998D22F8C98E }}

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'super-kanban'
        slot-name: 'Production'
        package: .
